In [2]:
import numpy as np
import pandas as pd
import scipy

In [150]:
# Initialize matrices for testing the algorithm
A = ([[ 956,    0,     1,   258/5],
       [5/2,    4,  13/2,   149/5],
       [  1,  3/2,     0,   67/10]])

b = [4, 7/2, 55]

c = [7/2, 0, 453, 6]

Eqin = [0, 0, 0]

A = np.float_(A)
b = np.float_(b)
c = np.float_(c)

In [151]:
# Define rows, cols lenght
rows = len(A)
cols = len(A[1])

# Initialize original r, s and their non_zeros
r = [0] * rows
s = [0] * cols

r_non_zeros = [0] * rows
s_non_zeros = [0] * cols

# Create r
for i in range(rows):
    row_non_zeros = 0
    for j in range(cols):
        if A[i][j] != 0:
            row_non_zeros += 1
            r_non_zeros[i] = row_non_zeros
            r[i] += abs(A[i][j]) 

print("Table A has the following Non-Zero elements per ROW:", r_non_zeros)
            
for i in range(rows):
    r[i] = r_non_zeros[i] / r[i]
            
# Update A and b
for i in range(rows):
    b[i] = np.dot(b[i], r[i])
    for j in range(cols):
        A[i][j] = np.dot(A[i][j], r[i])
        
# Create s
for j in range(cols):
    col_non_zeros = 0
    for i in range(rows):
        if A[i][j] != 0:
            col_non_zeros += 1
            s_non_zeros[j] = col_non_zeros
            s[j] += abs(A[i][j])
            
print("Table A after the update has the following Non-Zero elements per COL:", s_non_zeros)

for j in range(cols):
    s[j] = s_non_zeros[j] / s[j]
    
# Update A and c
for j in range(cols):
    c[j] = np.dot(c[j], s[j])
    for i in range(rows):
        A[i][j] = np.dot(A[i][j], s[j])
        
# Convert r, s to numpy arrays for rounding
r = np.asarray(r)
s = np.asarray(s)

# Rounding for simplicity
A = A.round(decimals=5)
b = b.round(decimals=5)
c = c.round(decimals=5)
r = r.round(decimals=5)
s = s.round(decimals=5)

print("\nA: \n", A)
print("\nb: ", b)
print("\nc: ", c)
print("\nr: ", r)
print("\ns: ", s)

Table A has the following Non-Zero elements per ROW: [3, 4, 3]
Table A after the update has the following Non-Zero elements per COL: [3, 2, 2, 3]

A: 
 [[2.50659 0.      0.00974 0.08987]
 [0.20596 0.86639 1.99026 1.63081]
 [0.28745 1.13361 0.      1.27932]]

b:  [1.190000e-02 3.271000e-01 1.793478e+01]

c:  [   3.08526    0.      1484.14847    3.51335]

r:  [0.00297 0.09346 0.32609]

s:  [0.8815  2.3176  3.27627 0.58556]
